name: Check PR Title

on:
  pull_request:
    types: ['opened', 'reopened', 'edited', 'synchronize']

jobs:
  check_pr_title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Branch
        uses: actions/checkout@v3

      - name: Check PR Title
        uses: rudderlabs/github-action-check-pr-title@v1.0.7
