name: Deploy Configurations To Sources Development DB

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Either triggered from develop branch or merged pull requests
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        env:
          HUSKY: 0
        run: |
          npm ci

      - name: Execute Unit Tests
        env:
          HUSKY: 0
        run: |
          npm run test

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Display Python Version
        run: |
          which python
          python -c "import sys; print(sys.version)"

      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip requests jsondiff

      - name: Display Working Directory Files
        run: |
          echo current directory
          pwd
          ls -a

      - name: Display Current Package Version
        run: echo $(jq -r .version package.json)

      - name: Deploy To Sources Development DB
        run: |
          echo "🍏 sources dev deployment complete."
